#!/usr/bin/env bash
# custom http response header on new ubuntu machine
# Install nginx on web-01 server
apt-get -y update
apt-get -y install nginx
sudo sed -i '/listen 80 default_server;/ a \\t add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
