#!/usr/bin/env bash
# Bash script that loops from 1 to 10

Message="Best School"

n=1
while [ "$n" -le 10 ]; do
	if [ "$n" -eq 4 ]; then
		echo -e "bad luck"

	elif [ "$n" -eq 8 ]; then
		echo -e "good luck"

	else
		echo -e "$Message"

	fi
	n="$((n+1))"
done
